function gaussianmat = mk_gaussian(varargin)
%MK_GAUSSIAN Converts a matrix to a Gaussain envelope.
%
%   GAUSSIANMAT = MK_GAUSSIAN(PIXELMAP, SD [,X0]) returns a matrix with the
%   size of PIXELMAP. Elements of the PIXELMAP are used as input values of a
%   Gaussain envelope with a standard deviation of SD pixles and a peak at X0.
%   Output values are not scaled: it is 1 at the peak of the Gaussian.
%
%   Arguments:
%      PIXELMAP - a matrix generated by MAP_* functions.
%      SD       - standard deviation of a Gaussian.
%      X0       - x-value of the peak, 0 if empty or not provided.
%
%   Example:
%     imshow(mk_gaussian(map_radial(200), 25));
%
%   See also MAP_RADIAL, MAP_LINEAR.

	pixelmap = parse_arg(varargin, 1, mfilename, 'pixelmap', [], {'numeric'}, {'nonempty', 'real', 'finite', 'nonnan'});
	sd       = parse_arg(varargin, 2, mfilename, 'sd',       [], {'numeric'}, {'scalar', 'real', 'finite', 'nonnan', 'positive'});
	x0       = parse_arg(varargin, 3, mfilename, 'x0',       0,  {'numeric'}, {'scalar', 'real', 'finite', 'nonnan'});

	gaussianmat = exp(-.5 * ((pixelmap - x0) / sd) .^ 2);
end